### ISSUE TITLE
Will the FireRays SDK source code be available?

### ISSUE THREAD

**Issue by p32blo** [GPUOpen-LibrariesAndSDKs/FireRays_SDK#1]
Is it correct to expect that the source code for the FireRays SDK will be released? Or will this simply be a mirror repository for the library binaries and sample app already available at the [AMD website](http://developer.amd.com/tools-and-sdks/graphics-development/firepro-sdk/firerays-sdk/)?

**Comment by yozhijk** [comment]
Hi p32blo,

This is going to be main repository for FireRays SDK, the one linked from the website is to be removed. There are currently no plans to open-source the intersector.

**Comment by p32blo** [comment]
Thank you! Could the Linux binary be available in any way before that? I'm not able even test a simple example right now.

**Comment by yozhijk** [comment]
Yes, I am planning to publish Linux and OSX binaries next week.

**Comment by p32blo** [comment]
Any updates yet?

**Comment by yozhijk** [comment]
Hi p32blo, 
Legal review takes a bit longer than expected. But hope to have it here early next week.

**Comment by yozhijk** [comment]
Hi p32blo,

I have just commited Linux binaries, please give it a try and let me know how it goes.

Thanks,
-Dmitry

**Comment by p32blo** [comment]
Thank you @yozhijk  !!

At first glance it seem to be working, but since `QueryIntersection` is only available for _complete path_ and not for _fast path_ I will have hold you on that confirmation. Will let you know of any development.

**Comment by yozhijk** [comment]
We finally made it open-source! So closing the issue
