### ISSUE TITLE
Missing resources ?

### ISSUE THREAD

**Issue by nearFar** [GPUOpen-LibrariesAndSDKs/FireRays_SDK#11]
Currently getting this error trying to run the app :

Can't load ../Resources/Textures/studio015.hdr image

There's confirmedly no actual /Textures/ Directory to be found in the Resource Directory.

**Comment by yozhijk** [comment]
I have added missing HDRI: https://github.com/GPUOpen-LibrariesAndSDKs/FireRays_SDK/commit/524dba5d8329f540d28e52eaddb98d8996941378
