### ISSUE TITLE
license

### ISSUE THREAD

**Issue by u56237z** [GPUOpen-LibrariesAndSDKs/FireRays_SDK#15]
I'm sorry if this is not the right place to ask, I just can't find anything around, I posted on AMD community forums but still no signs.
 
I am currently testing the FireRays library, the FireRays page states that "FireRays can be easily ditributed", but I cannot understand from the license file if the Library can be used in commercial closed-source applciations.
 
At first the license grants permission to use the Library to "create Derivative Works only for internal use", but later states that it also grants permission to "ditribute and sublicense ... the Object Code of the library solely as incorporated in Licensee Software to customers and end-users (collectively, Distribution Channel).. for use on AMD processors.."
 
so, just to be sure, may I use the Library (link an executable against the Library as shared/stati`c) in a closed-source, commercial application (possibly used by end-users on both AMD and non-AMD hardware) ?
 
thanks

**Comment by yozhijk** [comment]
Hi u56237z,

You can use the library in closed source commercial application no problem. AMD processors were there by mistake, so I will make sure we fix the license file. We are currently preparing an open-sourcing of FireRays, so it is going to be fully open-sourced under permissive MIT license in May anyway.

**Comment by u56237z** [comment]
Great.

Thank you
