### ISSUE TITLE
Multiple FireRay download points

### ISSUE THREAD

**Issue by Woking-34** [GPUOpen-LibrariesAndSDKs/FireRays_SDK#2]
Hi,

Could you please reorganize the availability/access points to the FireRay SDK. I mean, right now you can download the pack via:
- http://developer.amd.com/tools-and-sdks/graphics-development/firepro-sdk/
- https://github.com/amdadvtech
- https://github.com/GPUOpen-LibrariesAndSDKs/FireRays_SDK

Is this the "main" FireRay page? Can we expect future updates to the package? Thanks.

**Comment by yozhijk** [comment]
Primary download point is https://github.com/GPUOpen-LibrariesAndSDKs/FireRays_SDK
all other repos is to be removed. The library is getting regular updates.

**Comment by yozhijk** [comment]
The downloads have been removed from AMD FirePro page.
