### ISSUE TITLE
Issues running premake on OS X

### ISSUE THREAD

**Issue by ericwa** [GPUOpen-LibrariesAndSDKs/FireRays_SDK#26]
The README.md has:
```
./premake/osx/premake5 xcode4
```
but seems like the path should be:
```
./Tools/premake/osx/premake5 xcode4
```

Also, the premake5 executable needs the executable permission set, either in git, or by adding a `chmod +x ./Tools/premake/osx/premake5` to the getting started instructions

**Comment by yozhijk** [comment]
README part fixed in https://github.com/GPUOpen-LibrariesAndSDKs/FireRays_SDK/commit/dd5f54a32debd1930069a6849db956acc9786dbc
