### ISSUE TITLE
OS X: should have /usr/local/lib in library search path 

### ISSUE THREAD

**Issue by ericwa** [GPUOpen-LibrariesAndSDKs/FireRays_SDK#27]
- I installed OpenImageIO with homebrew as instructed in the README.md.
- generated the xcode project with `./premake/osx/premake5 xcode4`

When I build the "App" target in Xcode I get a linker error:
```
ld: warning: directory not found for option '-L../3rdParty/oiio16/lib/x64'
ld: library not found for -lOpenImageIO
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
The build was fixed by adding /usr/local/lib to the "Library Search Paths" setting in Xcode

**Comment by yozhijk** [comment]
Fixed in https://github.com/GPUOpen-LibrariesAndSDKs/FireRays_SDK/commit/1f082ab247bd6c93269a7f7a9938b8f2dd8c5467
