### ISSUE TITLE
Firerays 'Application Error'

### ISSUE THREAD

**Issue by Dimiz** [GPUOpen-LibrariesAndSDKs/FireRays_SDK#4]
I cloned this repository, download AMD APP SDK and, used all libs and header files given by AMD APP SDK. When i tried to run the program this error ocurred "The application was unable to start correctly". Can you help me?

My CPU is: Intel(R) Core(TM) i5-3230M
GPU is NVIDIA Geforce 610M
VS2015

**Comment by nearFar** [comment]
Same problem here. Is OpenCL 2.0 required for this ? Although i suppose then there would be an actual OpenCL related error.
I know OpenCL runs on my machine on other projects at least.

CPU : Core 2 Duo 8200
GPU : NVidia GTX 550 Ti
VS 2015

**Comment by nearFar** [comment]
Never mind, apparently a .dll was not copied over properly. Gotta make sure all the proper DLLs from the 3rdparty directories are present. Whoops.

**Comment by Dimiz** [comment]
Thank you!

**Comment by yozhijk** [comment]
Closing as resolved
