### ISSUE TITLE
Light passes only 2 transparent materials

### ISSUE THREAD

**Issue by DuracellTurtle** [GPUOpen-LibrariesAndSDKs/FireRays_SDK#47]
Currently it seems like no light can make it through 3rd transparent material in a row. At least as seen by camera. Attaching example image and obj file used. Windows use hardcoded glass material, the white wall on right is hardcoded carpaint and bally thingy is hardcoded light (emissive)

![error](https://cloud.githubusercontent.com/assets/11043907/16261698/d02c0ba2-386c-11e6-93e7-67c61f655f12.PNG)

[glass_test.zip](https://github.com/GPUOpen-LibrariesAndSDKs/FireRays_SDK/files/327417/glass_test.zip)

**Comment by yozhijk** [comment]
This is because of

        // Initialize first pass
        for (int pass = 0; pass < 5; ++pass)
        {

in ptrenderer.cpp. So the renderer is calculating max 5 bounces, I did have time to expose it in the api just yet, but feel free to modify.
