### ISSUE TITLE
Build on Ubuntu

### ISSUE THREAD

**Issue by normandrobert** [GPUOpen-LibrariesAndSDKs/FireRays_SDK#5]
Hi
I have managed to build and run the older code from the AMD website in Unbuntu 14.04.3 LTS by making my own App/Makefile some months ago.  The app worked/works with cough NV???? HW and drivers obtained via apt-get. There is some glitchyness at startup but the window updates fine following mouse events. Impressive!

I noticed recent commits on github "official version" so I cloned the repo and had some issues:
git clone https://github.com/GPUOpen-LibrariesAndSDKs/FireRays_SDK.git
cd FireRays_SDK
// Not premake 4 as stated in the instructions
// Not executable..
chmod +x ./premake/linux64/premake5
./premake/linux64/premake5 gmake
// make does not work as instructed with "config=release64" so I did this instead
make
// Compilation seems ok but I am having link issues. I am showing the second make attempt which does the link step only:
robert@claire2:~/Dropbox/FireRays_SDK$ make
==== Building CLW (debug_x64) ====
==== Building App (debug_x64) ====
Linking App
/usr/bin/ld: cannot find -lFireRays64

The library name "FireRays/lib/x64/FireRays64.lib " does not observe the conventional Unices naming conventions i.e. libXXX.a/so. I am not familiar with premake and friends but I don't expect 
App/Makefile: "LIBS += ../Bin/Debug/x64/libCLW64D.a -lFireRays64 -lOpenImageIO -lglut -lGLEW -lGL"
with -lFireRays64 seen above to work with your naming convention. So I have hacked the lines (debug and release) in App/Makefile to 
LIBS += ../Bin/Release/x64/libCLW64.a ../FireRays/lib/x64/FireRays64.lib -lOpenCL -lOpenImageIO -lglut -lGLEW -lGL
which got rid of most but not all link problems.

make
==== Building CLW (debug_x64) ====
==== Building App (debug_x64) ====
Linking App
obj/x64/Debug/frrenderer.o: In function `FrRenderer::FrRenderer(CLWContext, int)':
/home/robert/Dropbox/FireRays_SDK/App/frrenderer.cpp:124: undefined reference to `FireRays::IntersectionApiCL::CreateFromOpenClContext(int, _cl_context*, _cl_device_id**, _cl_command_queue**, int)'
obj/x64/Debug/frrenderer.o: In function `FrRenderer::~FrRenderer()':
/home/robert/Dropbox/FireRays_SDK/App/frrenderer.cpp:158: undefined reference to `FireRays::IntersectionApi::Delete(FireRays::IntersectionApi*)'
collect2: error: ld returned 1 exit status
make[1]: *** [../Bin/Debug/x64/App64D] Error 1
make: *** [App] Error 2

**Comment by yozhijk** [comment]
Hi normandrobert,

Currently binaries for Linux are missing for this repo. And the previous version you were using is not compatibe with the current interface. I will publish Linux binaries shortly,

**Comment by normandrobert** [comment]
This is an important piece of software that has applications in my field which involves modelling of x-ray primary radiation transmission. It is important that it can find hidden intersections because x-ray are not fully absorbed by the first material that is encountered. The eventual availability of source code increases confidence that one can depend on it in the future as well. Please note that there was another problem with the build for the old code and the newer github code that I did not draw attention to but can be seen above: it needs the OpenCL library -lOpenCL . Awaiting the "new" libFireRays64.a/so! 

I am however unclear regarding the usage of the library and thus I have a question. If I write a simple application using FireRays::IntersectionApiCL as outlined in code fragments on the AMD web page, I do not need to write anything OpenCL related or include some .cl files etc. as is the case with the example you provide? So just include the header and link to the right libs correct?

It seems that in your example you are not using FireRays::IntersectionApiCL::Create() but are instead using some existing context because you are using OpenCl already for something else?  My attempt to create a very simple program based on the code fragment shown on the AMD Web page failed. I got an exception in Create(). I thought that after getting your more complicated application working on my Linux box that it would be easy to get a simple "hello world" case working but I was wrong :( so I am wondering if I have some fundamental misunderstanding regading the software hence my question... Regards

**Comment by u56237z** [comment]
Hi, any news concerning the linux binaries? I really want to try this lib. thanks

**Comment by yozhijk** [comment]
Hi u56237z, normandrobert,

I have just commited new library release with Linux binaries. Please try and let me know if it works for you. We tested it on Ubuntu 14.04 with proprietary driver. Note, that sample renderer requires OpenImageIO to be installed.

Thanks,
-Dmitry

**Comment by sshinderman** [comment]
btw -- in the readme for the linux step it has make config=release64 but the Makefile looks like it has debug_x64 and release_x64 as the targets.

**Comment by u56237z** [comment]
Grea! TY

**Comment by yozhijk** [comment]
@beasterio , could you check make targets mentioned by @sshinderman and update readme if necessary?

Thanks,
-Dmitry

**Comment by u56237z** [comment]
Tried and works perfectly on Mint 17 + CPU i7 only (an old 720QM), the documentation on the FireRays page is outdated, but looking at the header it is pretty easy to figure the changes

**Comment by yozhijk** [comment]
Closing as resolved
