### ISSUE TITLE
error: redefinition of '__float4' as different kind of symbol

### ISSUE THREAD

**Issue by ericwa** [GPUOpen-LibrariesAndSDKs/FireRays_SDK#59]
Setup:
- OS X 10.11.5
- FireRays built with `./Tools/premake/osx/premake5 --embed_kernels gmake` and `make config=debug_x64`

I'm getting an exception when calling `FireRays::IntersectionApi::Create(int)` in my own application which is linked to `libFireRays64d.dylib`.

The exception thrown is at `CLWProgram.cpp:100`, i.e. the `clBuildProgram` call has failed.
This is the first error in the build log that gets printed to stdout:
```
<program source>:103:8: error: redefinition of '__float4' as different kind of symbol
float4 make_float4(float x, float y, float z, float w) 
       ^
/System/Library/Frameworks/OpenCL.framework/Versions/A/lib/clang/3.2/include/cl_kernel.h:3226:31: note: expanded from macro 'make_float4'
#define make_float4(A,B,C,D) (float4)((A),(B),(C),(D))
                              ^
```

This error should be impossible because the make_float4 definition in FireRays is guarded by`#ifndef APPLE`...  so it looks like the buildopts passed to `clBuildProgram` (including `-D APPLE`) are being ignored for some reason.

As a guess, I tried changing `-I.` to `-I .` in the buildopts string at `CLWProgram.cpp:75` and now the`FireRays::IntersectionApi::Create()` call succeeds!

**Comment by yozhijk** [comment]
Hi @ericwa ,

Wow, that's a weird issue. Nice catch! Would you create a pull request or prefer me to apply your fix?
