### ISSUE TITLE
OS X Build Failing

### ISSUE THREAD

**Issue by Geenz** [GPUOpen-LibrariesAndSDKs/FireRays_SDK#6]
When I attempt to build with `./premake/osx/premake5 xcode4`, I get the following output:
```
Error: [string "src/_premake_main.lua"]:45: module 'xcode' not found:
	no field package.preload['xcode']
	no file './xcode.lua'
	no file '/usr/local/share/lua/5.1/xcode.lua'
	no file '/usr/local/share/lua/5.1/xcode/init.lua'
	no file '/usr/local/lib/lua/5.1/xcode.lua'
	no file '/usr/local/lib/lua/5.1/xcode/init.lua'
	no file './xcode.so'
	no file '/usr/local/lib/lua/5.1/xcode.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
```

**Comment by Geenz** [comment]
Updating the included version of premake5 to a newer version fixes this.

**Comment by yozhijk** [comment]
Hi Geenz,

I have published OSX binaries. It has been tested on AMD-based Mac Pro and several Intel HD based laptops. NVIDIA based Macs have not been tested yet.

Thanks,
-Dmitry

**Comment by Geenz** [comment]
Thanks @yozhijk. Just tested it on my side, everything seems to be as it should, with a minor exception (library search path on OS X wasn't setup properly for OpenImageIO - but that's easy to fix).

**Comment by yozhijk** [comment]
Closing as resolved
