### ISSUE TITLE
Windows build error:C2143

### ISSUE THREAD

**Issue by JaniKallankari** [GPUOpen-LibrariesAndSDKs/FireRays_SDK#7]
I use Visual Studio 2012 Pro to compile FireRays. I got following error:
1>  CLWProgram.cpp
1>d:\firerays_sdk-master\clw\CLWContext.h(76): error C2143: syntax error : missing ',' before '...' (CLWParallelPrimitives.cpp)
1>d:\firerays_sdk-master\clw\CLWContext.h(76): error C2061: syntax error : identifier 'Types' (CLWParallelPrimitives.cpp)
1>d:\firerays_sdk-master\clw\CLWContext.h(77): error C2143: syntax error : missing ',' before '...' (CLWParallelPrimitives.cpp)
1>d:\firerays_sdk-master\clw\CLWContext.h(77): error C2061: syntax error : identifier 'Types' (CLWParallelPrimitives.cpp)
1>d:\firerays_sdk-master\clw\CLWContext.h(78): error C2143: syntax error : missing ',' before '...' (CLWParallelPrimitives.cpp)
1>d:\firerays_sdk-master\clw\CLWContext.h(78): error C2061: syntax error : identifier 'Types' (CLWParallelPrimitives.cpp)
1>d:\firerays_sdk-master\clw\CLWContext.h(150): error C2143: syntax error : missing ',' before '...' (CLWParallelPrimitives.cpp)

Any idea what's causing errors?

**Comment by yozhijk** [comment]
Closing as resolved
