### ISSUE TITLE
Add dll that uses VS 2013 redistributables

### ISSUE THREAD

**Issue by deanmark** [GPUOpen-LibrariesAndSDKs/FireRays_SDK#8]
Current dll is compiled with VS2015 and requires the VS2015 redistributables. It would be useful to have a version compiled with VS2013 requiring the VS2013 redistributables. Alternatively please supply a static library.

Thanks

**Comment by yozhijk** [comment]
Hi deanmark,

It is on my list. Stay tuned.

**Comment by yozhijk** [comment]
Seems like it is not needed anymore since the library is now open-source!
